module.exports = {
    name: "project",
    database:"store",
    display: "name",
    schema: {
       name: {
         unique:true,
          input: "text",
          required: true,
          type: "string",
       },
       database: {
          input: "text",
          required: true,
          type: "string",
       },
       
    },
    lifecycle: {
       get: {
        preRule:[],
        modify:[],
        role: ["admin"],
        rule:[],
        filter:[],
        effect:[],  
       },
       getAll: {
        preRule:[],
        modify:[],
        role: ["admin"],
        rule:[],
        filter:[],
        effect:[],  
       },
       update: {
        preRule:[],
        modify:[],
        role: ["admin"],
        rule:[],
        filter:[],
        effect:[],  
       },
       post: {
        preRule:[],
        modify:[],
        role: ["admin"],
        rule:[],
        filter:[],
        effect:[],  
       },
       delete: {
        preRule:[],
        modify:[],
        role: ["admin"],
        rule:[],
        filter:[],
        effect:[],  
       },
       count: {    
          preRule:[],
          modify:[],
          role: ["admin"],
          rule:[],
          filter:[],
          effect:[],       
       },
    },
    methods:{},
    mixin:[],
 };